version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: host
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: brain-agricuture-db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: